#!/usr/bin/env bash
# 预渲染部署 profile：Helm chart 为拓扑唯一权威源，本脚本把 chart + profile
# values 渲染成 standalone YAML（deploy/rendered/<profile>/），供元启动
# "读目录 -> kubectl apply" 消费——引导链零 helm 依赖。
#
# 用法：
#   bash deploy/scripts/render-deploy.sh           # 渲染全部 profile，写回 deploy/rendered/
#   bash deploy/scripts/render-deploy.sh --check   # CI 新鲜度门禁：重渲染到临时目录，
#                                                  # 与已提交产物 diff，漂移即失败
#
# 渲染产物是构建产物，不要手改；改拓扑请动 chart templates / values / profile，
# 然后重跑本脚本并一并提交。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHART_DIR="$REPO_ROOT/deploy/helm/cogneva"
PROFILES_DIR="$CHART_DIR/profiles"
RENDERED_DIR="$REPO_ROOT/deploy/rendered"

PROFILES=(k3s-single k3s-multi k8s-standard)

render_profile() {
  local profile="$1" out_dir="$2"
  mkdir -p "$out_dir"
  find "$out_dir" -name '*.yaml' -delete
  helm template cogneva "$CHART_DIR" \
    -f "$PROFILES_DIR/$profile.yaml" \
    --namespace cogneva \
    > "$out_dir/.rendered.yaml"
  python3 - "$out_dir/.rendered.yaml" "$out_dir" "$profile" <<'PY'
import os, re, sys

src, out_dir, profile = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src).read()
header = (
    "# GENERATED by deploy/scripts/render-deploy.sh — DO NOT EDIT.\n"
    f"# Source: helm chart deploy/helm/cogneva + profiles/{profile}.yaml\n"
    "# Change chart templates / values / profile, then re-run render-deploy.sh.\n"
)
docs = re.split(r"(?m)^---\s*$", text)

try:
    import yaml
except ImportError:
    sys.exit("需要 python3-yaml（与 check-deploy-parity.sh 同一依赖）")

order = {
    "Namespace": "00", "StorageClass": "05", "Secret": "08",
    "ConfigMap": "10", "ServiceAccount": "15", "Role": "16",
    "ClusterRole": "16", "RoleBinding": "17", "ClusterRoleBinding": "17",
    "PersistentVolumeClaim": "20", "Service": "30",
    "DaemonSet": "40", "Deployment": "41", "StatefulSet": "42",
    "NetworkPolicy": "50", "Ingress": "60", "Middleware": "70",
}
written = []
for doc in docs:
    doc = doc.strip("\n")
    if not doc.strip():
        continue
    parsed = yaml.safe_load(doc)
    if not parsed or not parsed.get("kind"):
        continue
    kind = parsed["kind"]
    name = parsed["metadata"]["name"]
    prefix = order.get(kind, "90")
    fname = f"{prefix}-{kind.lower()}-{name}.yaml"
    with open(os.path.join(out_dir, fname), "w") as f:
        f.write(header + doc + "\n")
    written.append(fname)

os.remove(src)
print(f"{profile}: {len(written)} resources rendered")
PY
}

if [[ "${1:-}" == "--check" ]]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  for p in "${PROFILES[@]}"; do
    render_profile "$p" "$tmp/$p"
    if ! diff -r "$tmp/$p" "$RENDERED_DIR/$p" >/dev/null 2>&1; then
      echo "FAIL: deploy/rendered/$p 已过期（与 chart/profile 重渲染结果不一致）。"
      echo "      请本地运行 bash deploy/scripts/render-deploy.sh 并提交产物。"
      diff -r "$tmp/$p" "$RENDERED_DIR/$p" | head -40 || true
      exit 1
    fi
  done
  echo "RENDER FRESHNESS OK：deploy/rendered/ 与 chart/profiles 一致"
else
  for p in "${PROFILES[@]}"; do
    render_profile "$p" "$RENDERED_DIR/$p"
  done
  echo "渲染完成：$RENDERED_DIR"
fi
