//! PR publisher — turns a generated patch into a pull request.
//!
//! Flow (design doc §3.7): branch from `base_branch` in a local working
//! copy → `git apply` the unified diff → commit signed as the bot identity
//! → push → open the PR via the platform provider.
//!
//! The working copy must be a git clone of the target repository with a
//! push-capable `origin` remote; credentials stay in the main process and
//! never enter the sandbox.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use cog_core::{BotIdentityConfig, GeneratedPatch, GitHubIntegrationConfig};

use crate::error::{CogGitHubError, Result};
use crate::provider::{CodePlatformProvider, CreatePullRequest, PlatformPullRequest};

/// Publishes patches as pull requests.
#[derive(Debug)]
pub struct GitHubPrPublisher {
    workdir: PathBuf,
    config: GitHubIntegrationConfig,
}

impl GitHubPrPublisher {
    /// Create a publisher operating on the given local working copy.
    pub fn new(workdir: impl Into<PathBuf>, config: GitHubIntegrationConfig) -> Self {
        Self {
            workdir: workdir.into(),
            config,
        }
    }

    /// Apply `patch_content` on a fresh branch and open a PR linking
    /// `issue_number`. Returns the created PR.
    pub async fn publish_patch(
        &self,
        provider: &dyn CodePlatformProvider,
        patch_id: &str,
        patch_content: &str,
        issue_number: u64,
        issue_title: &str,
    ) -> Result<PlatformPullRequest> {
        let branch = format!("cogneva/fix-{}-{}", issue_number, sanitize(patch_id));
        let identity = &self.config.bot_identity;
        self.publish(
            provider,
            patch_content,
            &branch,
            &format!(
                "fix(issue #{}): {}\n\nAutomated patch {} generated by Cogneva.\n\n{}",
                issue_number,
                issue_title,
                patch_id,
                identity_signoff(identity)
            ),
            &format!("[Cogneva] fix issue #{}: {}", issue_number, issue_title),
            &format!(
                "Fixes #{}\n\nPatch `{}` generated autonomously by Cogneva.\n\n{}",
                issue_number, patch_id, self.config.conversation.bot_signature
            ),
        )
        .await
    }

    /// Branch from the remote base, apply the patch, commit, push, open PR.
    async fn publish(
        &self,
        provider: &dyn CodePlatformProvider,
        patch_content: &str,
        branch: &str,
        commit_message: &str,
        pr_title: &str,
        pr_body: &str,
    ) -> Result<PlatformPullRequest> {
        let identity = &self.config.bot_identity;
        let base = self.config.base_branch.clone();

        // Branch straight from the remote base so a reused workdir never
        // builds on a stale local base.
        self.git(&["fetch", "origin", &base]).await?;
        let remote_base = format!("origin/{base}");

        let apply_result = async {
            self.git(&["checkout", "-B", branch, &remote_base]).await?;
            self.apply_patch(patch_content).await
        }
        .await;
        if let Err(e) = apply_result {
            // Best-effort cleanup so the next attempt starts clean.
            let _ = self.git(&["checkout", "--detach", &remote_base]).await;
            let _ = self.git(&["branch", "-D", branch]).await;
            return Err(e);
        }

        self.git(&["add", "-A"]).await?;
        self.git(&[
            "-c",
            &format!("user.name={}", identity.name),
            "-c",
            &format!("user.email={}", identity.email),
            "commit",
            "-m",
            commit_message,
        ])
        .await?;
        self.git(&["push", "-u", "origin", branch, "--force-with-lease"])
            .await?;

        let pr = provider
            .create_pull_request(CreatePullRequest {
                title: pr_title.to_string(),
                body: pr_body.to_string(),
                head_branch: branch.to_string(),
                base_branch: base,
                draft: false,
            })
            .await?;

        Ok(pr)
    }

    async fn apply_patch(&self, patch_content: &str) -> Result<()> {
        let tmp = tempfile::NamedTempFile::new()?;
        std::fs::write(tmp.path(), patch_content)?;
        let output = tokio::process::Command::new("git")
            .arg("apply")
            .arg("--whitespace=nowarn")
            .arg(tmp.path())
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git apply failed: {}",
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }

    async fn git(&self, args: &[&str]) -> Result<()> {
        let output = tokio::process::Command::new("git")
            .args(args)
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git {:?} failed: {}",
                args,
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }
}

fn sanitize(patch_id: &str) -> String {
    patch_id
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '-' | '_'))
        .collect()
}

fn identity_signoff(identity: &BotIdentityConfig) -> String {
    format!("Signed-off-by: {} <{}>", identity.name, identity.email)
}

/// True when `workdir` looks like a usable git working copy.
pub async fn is_git_workdir(workdir: &Path) -> bool {
    workdir.join(".git").exists()
}

/// PatchSink implementation that turns collaboration-generated patches into
/// GitHub pull requests (CI-failure fixes and other autonomous patches that
/// are not tied to an issue).
pub struct GitHubPatchSink {
    publisher: GitHubPrPublisher,
    provider: Arc<dyn CodePlatformProvider>,
}

impl std::fmt::Debug for GitHubPatchSink {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GitHubPatchSink").finish_non_exhaustive()
    }
}

impl GitHubPatchSink {
    /// Create a sink from a publisher and the platform provider used to open
    /// pull requests.
    pub fn new(publisher: GitHubPrPublisher, provider: Arc<dyn CodePlatformProvider>) -> Self {
        Self {
            publisher,
            provider,
        }
    }
}

#[async_trait::async_trait]
impl cog_core::PatchSink for GitHubPatchSink {
    async fn submit_patch(&self, patch: GeneratedPatch) -> cog_core::SFResult<String> {
        let branch = format!("cogneva/auto-{}", sanitize(&patch.patch_id));
        let title = patch
            .goal
            .lines()
            .next()
            .unwrap_or("autonomous patch")
            .chars()
            .take(70)
            .collect::<String>();
        let mut body = format!(
            "Patch `{}` generated autonomously by Cogneva (PGE mode: {}).\n\n## Goal\n\n{}",
            patch.patch_id, patch.pge_mode, patch.goal
        );
        if let Some(ref rationale) = patch.rationale {
            body.push_str(&format!("\n\n## Rationale\n\n{rationale}"));
        }
        if let Some(score) = patch.self_review_score {
            body.push_str(&format!("\n\nSelf-review score: {score:.2}"));
        }
        if !patch.affected_files.is_empty() {
            body.push_str(&format!(
                "\n\nAffected files: {}",
                patch.affected_files.join(", ")
            ));
        }

        let identity = &self.publisher.config.bot_identity;
        let commit_message = format!(
            "chore(cogneva): autonomous patch {}\n\n{}\n\n{}",
            patch.patch_id,
            title,
            identity_signoff(identity)
        );

        let pr = self
            .publisher
            .publish(
                self.provider.as_ref(),
                &patch.content,
                &branch,
                &commit_message,
                &format!("[Cogneva] {title}"),
                &body,
            )
            .await
            .map_err(|e| cog_core::SFError::Internal(e.to_string()))?;
        Ok(pr.url)
    }
}

/// Ensure `config.pr_workdir` is a usable git clone of the target repo.
///
/// Missing directories are created by cloning. Remote selection:
/// `COGNEVA_GITHUB_USE_SSH` set → `ssh://git@github.com:22/...` (for networks
/// where github.com HTTPS is blocked; authentication comes from
/// `GIT_SSH_COMMAND` in the process environment). Otherwise an
/// `x-access-token` HTTPS remote when a platform token is available, falling
/// back to anonymous HTTPS. Existing working copies are returned as-is.
pub async fn ensure_workdir(
    config: &GitHubIntegrationConfig,
    token: Option<&str>,
) -> Result<PathBuf> {
    let workdir = PathBuf::from(&config.pr_workdir);
    if is_git_workdir(&workdir).await {
        return Ok(workdir);
    }
    if let Some(parent) = workdir.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    let url = if std::env::var_os("COGNEVA_GITHUB_USE_SSH").is_some() {
        format!("ssh://git@github.com:22/{}.git", config.repo)
    } else {
        match token {
            Some(t) => format!("https://x-access-token:{t}@github.com/{}.git", config.repo),
            None => format!("https://github.com/{}.git", config.repo),
        }
    };
    let output = tokio::process::Command::new("git")
        .arg("clone")
        .arg(&url)
        .arg(&workdir)
        .output()
        .await?;
    if !output.status.success() {
        // Never leak the token into logs.
        let mut stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        if let Some(t) = token.filter(|t| !t.is_empty()) {
            stderr = stderr.replace(t, "***");
        }
        return Err(CogGitHubError::Provider(format!(
            "git clone failed: {stderr}"
        )));
    }
    Ok(workdir)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_strips_unsafe_chars() {
        assert_eq!(sanitize("patch-AB_12/.."), "patch-AB_12");
    }
}
