//! PR publisher — turns a generated change into a pull request.
//!
//! Flow (design doc §3.7): branch from `base_branch` in a local working
//! copy → `git apply` the unified diff → commit signed as the bot identity
//! → push → open the PR via the platform provider.
//!
//! The working copy must be a git clone of the target repository with a
//! push-capable `origin` remote; credentials stay in the main process and
//! never enter the sandbox.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::config::{BotIdentityConfig, GitHubIntegrationConfig};
use cog_core::{parse_diff_affected_files, GeneratedChange};

use crate::error::{CogGitHubError, Result};
use crate::provider::{CodePlatformProvider, CreatePullRequest, ForkTarget, PlatformPullRequest};

/// Where contribution branches are pushed for one publish round.
#[derive(Debug, Clone)]
enum PushTarget {
    /// Direct push to the configured upstream repo (owner/collaborator
    /// credential); the PR is same-repo with a bare branch head.
    Upstream,
    /// Push to the contributor's own fork; the PR is cross-fork with head
    /// `<owner>:<branch>`.
    Fork(ForkTarget),
}

impl PushTarget {
    /// Git remote name in the working copy.
    fn remote(&self) -> &'static str {
        match self {
            PushTarget::Upstream => "origin",
            PushTarget::Fork(_) => "fork",
        }
    }

    /// PR `head` value: bare branch for same-repo, `<fork-owner>:<branch>`
    /// for cross-fork.
    fn pr_head(&self, branch: &str) -> String {
        match self {
            PushTarget::Upstream => branch.to_string(),
            PushTarget::Fork(f) => format!("{}:{}", f.owner, branch),
        }
    }
}

/// Publishes changes as pull requests.
#[derive(Debug)]
pub struct GitHubPrPublisher {
    workdir: PathBuf,
    config: GitHubIntegrationConfig,
}

impl GitHubPrPublisher {
    /// Create a publisher operating on the given local working copy.
    pub fn new(workdir: impl Into<PathBuf>, config: GitHubIntegrationConfig) -> Self {
        Self {
            workdir: workdir.into(),
            config,
        }
    }

    /// Apply `change_content` on a fresh branch and open a PR linking
    /// `issue_number`. Returns the created PR.
    pub async fn publish_change(
        &self,
        provider: &dyn CodePlatformProvider,
        change_id: &str,
        change_content: &str,
        issue_number: u64,
        issue_title: &str,
    ) -> Result<PlatformPullRequest> {
        let branch = format!("cogneva/fix-{}-{}", issue_number, sanitize(change_id));
        let identity = &self.config.bot_identity;
        let pr_body = format!(
            "Fixes #{}\n\nChange `{}` generated autonomously by Cogneva.\n\n{}\n\n{}",
            issue_number,
            change_id,
            self.config.conversation.bot_signature,
            metadata_block(identity, None, Some(&format!("#{issue_number}")))
        );
        self.publish(
            provider,
            change_content,
            &branch,
            &format!(
                "fix(issue #{}): {}\n\nAutomated change {} generated by Cogneva.\n\n{}",
                issue_number,
                issue_title,
                change_id,
                identity_signoff(identity)
            ),
            &format!("[Cogneva] fix issue #{}: {}", issue_number, issue_title),
            &pr_body,
        )
        .await
    }

    /// Resolve where this round's branch must be pushed: upstream when the
    /// connected credential has push access, otherwise the contributor's
    /// automatically ensured fork.
    async fn resolve_target(&self, provider: &dyn CodePlatformProvider) -> Result<PushTarget> {
        match provider.ensure_push_target().await? {
            Some(fork) => {
                tracing::info!(
                    fork = %fork.full_name,
                    new = fork.newly_created,
                    "contribution account has no push access; using fork"
                );
                Ok(PushTarget::Fork(fork))
            }
            None => Ok(PushTarget::Upstream),
        }
    }

    /// Make sure the git remote for `target` exists in the working copy and
    /// points at the right URL. Base fetching always stays on `origin` (the
    /// upstream); the fork remote is push-only.
    async fn setup_remote(&self, target: &PushTarget) -> Result<()> {
        let ForkTarget {
            full_name,
            newly_created,
            ..
        } = match target {
            PushTarget::Upstream => return Ok(()),
            PushTarget::Fork(f) => f,
        };
        let token = self
            .config
            .primary_account()
            .ok()
            .and_then(|a| a.resolve_token().ok());
        let url = select_remote_url_for(
            &self.config,
            token.as_deref(),
            git_proxy_base().as_deref(),
            std::env::var_os("COGNEVA_GITHUB_USE_SSH").is_some(),
            full_name,
        );
        // remove + add: idempotent across coordinate changes (renamed fork),
        // and never touches origin.
        let _ = self.git(&["remote", "remove", "fork"]).await;
        self.git(&["remote", "add", "fork", &url]).await?;
        if *newly_created {
            // A just-created fork propagates to the git backend asynchronously;
            // fetch it once the remote is wired so the push below has the
            // repository reachable, and the push itself still retries.
            let _ = self.git(&["fetch", "fork"]).await;
        }
        Ok(())
    }

    /// Branch from the remote base, apply the change, commit, push, open PR.
    async fn publish(
        &self,
        provider: &dyn CodePlatformProvider,
        change_content: &str,
        branch: &str,
        commit_message: &str,
        pr_title: &str,
        pr_body: &str,
    ) -> Result<PlatformPullRequest> {
        // Whitelist gate before any git operation: a change that touches
        // configs, secrets, deploy manifests, or business data must never be
        // pushed to the public repo. Fail closed — do not trust the generator.
        ensure_contribution_allowed(change_content)?;

        let identity = &self.config.bot_identity;
        let base = self.config.base_branch.clone();
        let target = self.resolve_target(provider).await?;
        self.setup_remote(&target).await?;
        let push_remote = target.remote();
        let head_ref = target.pr_head(branch);

        // Branch straight from the remote base so a reused workdir never
        // builds on a stale local base.
        self.git(&["fetch", "origin", &base]).await?;
        let remote_base = format!("origin/{base}");

        let apply_result = async {
            self.git(&["checkout", "-B", branch, &remote_base]).await?;
            self.apply_change(change_content).await
        }
        .await;
        if let Err(e) = apply_result {
            // Best-effort cleanup so the next attempt starts clean.
            let _ = self.git(&["checkout", "--detach", &remote_base]).await;
            let _ = self.git(&["branch", "-D", branch]).await;
            return Err(e);
        }

        self.git(&["add", "-A"]).await?;
        self.git(&[
            "-c",
            &format!("user.name={}", identity.git_author_name()),
            "-c",
            &format!("user.email={}", identity.git_author_email()),
            "commit",
            "-m",
            commit_message,
        ])
        .await?;
        self.push_with_fork_retry(push_remote, branch, &target)
            .await?;

        let pr = provider
            .create_pull_request(CreatePullRequest {
                title: pr_title.to_string(),
                body: pr_body.to_string(),
                head_branch: head_ref,
                base_branch: base,
                draft: false,
            })
            .await?;

        // Cross-validation discovery filters on this label; without it no bot
        // would ever pick the PR up. Best-effort: a provider without label
        // support must not fail the publish itself.
        if let Err(e) = provider
            .add_labels(
                pr.number,
                &[crate::cross_validation::CROSS_VALIDATION_LABEL.to_string()],
            )
            .await
        {
            tracing::warn!(
                pr = pr.number,
                error = %e,
                "failed to attach cross-validation label; PR will not be picked up by bot board"
            );
        }

        Ok(pr)
    }

    /// Push the branch to the chosen remote. For a freshly created fork the
    /// git backend may reject pushes for a few seconds while propagation
    /// completes; retry briefly in that case. Upstream pushes are tried once
    /// (a real permission error must surface loudly).
    async fn push_with_fork_retry(
        &self,
        remote: &str,
        branch: &str,
        target: &PushTarget,
    ) -> Result<()> {
        let attempts = match target {
            PushTarget::Fork(f) if f.newly_created => 4,
            _ => 1,
        };
        let mut last_err = None;
        for attempt in 0..attempts {
            match self
                .git(&["push", "-u", remote, branch, "--force-with-lease"])
                .await
            {
                Ok(()) => return Ok(()),
                Err(e) => {
                    last_err = Some(e);
                    if attempt + 1 < attempts {
                        tracing::info!(
                            remote,
                            branch,
                            attempt,
                            "fork not pushable yet; retrying after propagation delay"
                        );
                        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                    }
                }
            }
        }
        Err(last_err
            .unwrap_or_else(|| CogGitHubError::Provider("git push failed without an error".into())))
    }

    async fn apply_change(&self, change_content: &str) -> Result<()> {
        let tmp = tempfile::NamedTempFile::new()?;
        std::fs::write(tmp.path(), change_content)?;
        let output = tokio::process::Command::new("git")
            .arg("apply")
            .arg("--whitespace=nowarn")
            .arg(tmp.path())
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git apply failed: {}",
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }

    async fn git(&self, args: &[&str]) -> Result<()> {
        let output = tokio::process::Command::new("git")
            .args(args)
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git {:?} failed: {}",
                args,
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }

    /// Whether a branch already exists on the given remote (idempotency guard
    /// for the staged-change flush after the contribution channel comes up).
    /// Network errors are treated as "unknown → not published" so a transient
    /// failure still lets the normal publish path retry and fail loudly.
    pub(crate) async fn remote_branch_exists(&self, remote: &str, branch: &str) -> bool {
        let Ok(output) = tokio::process::Command::new("git")
            .args(["ls-remote", "--heads", remote, branch])
            .current_dir(&self.workdir)
            .output()
            .await
        else {
            return false;
        };
        output.status.success() && !output.stdout.trim_ascii().is_empty()
    }

    /// Resolve the push target (upstream or auto-fork) and wire its remote in
    /// the working copy. Used by the idempotency check so it probes the same
    /// remote the subsequent publish pushes to. Errors degrade to "not
    /// published" so the normal publish path surfaces the real failure.
    pub(crate) async fn prepare_push_remote(
        &self,
        provider: &dyn CodePlatformProvider,
    ) -> Option<&'static str> {
        let target = self.resolve_target(provider).await.ok()?;
        self.setup_remote(&target).await.ok()?;
        Some(target.remote())
    }
}

fn sanitize(change_id: &str) -> String {
    change_id
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '-' | '_'))
        .collect()
}

fn identity_signoff(identity: &BotIdentityConfig) -> String {
    format!(
        "Signed-off-by: {} <{}>",
        identity.git_author_name(),
        identity.git_author_email()
    )
}

/// Whitelist gate for public contributions. Every path the diff touches must
/// fall inside the generic, shareable surface: Rust sources under
/// `crates/**/src/`, files under `prompts/`, or the root README/CHANGELOG.
/// Everything else — deploy manifests, configs, secrets, business data — is
/// hard-rejected before anything is pushed. A diff from which no paths can be
/// parsed is rejected as well (fail closed).
pub fn ensure_contribution_allowed(diff: &str) -> Result<()> {
    let files = parse_diff_affected_files(diff)
        .map_err(|e| CogGitHubError::PrivacyRejected(e.to_string()))?;
    let denied: Vec<&str> = files
        .iter()
        .map(String::as_str)
        .filter(|p| !is_allowed_path(p))
        .collect();
    if denied.is_empty() {
        Ok(())
    } else {
        Err(CogGitHubError::PrivacyRejected(format!(
            "change touches non-contributable paths: {} \
             (whitelist: crates/**/src/**/*.rs, prompts/**, root README/CHANGELOG)",
            denied.join(", ")
        )))
    }
}

/// Whether a single repo-relative path is inside the contribution whitelist.
fn is_allowed_path(path: &str) -> bool {
    let p = path.strip_prefix("./").unwrap_or(path);

    if let Some(rest) = p.strip_prefix("crates/") {
        // crates/<crate>/src/<...>.rs — the src segment is mandatory and the
        // final path segment must be a Rust source file.
        let mut segs = rest.split('/');
        let crate_seg = segs.next();
        if crate_seg.is_none_or(|s| s.is_empty()) || segs.next() != Some("src") {
            return false;
        }
        return matches!(segs.next_back(), Some(file) if file.ends_with(".rs"));
    }

    if let Some(rest) = p.strip_prefix("prompts/") {
        // Any file under prompts/, but no traversal/empty segments.
        return !rest.is_empty()
            && rest
                .split('/')
                .all(|seg| !seg.is_empty() && seg != "." && seg != "..");
    }

    // Root-level README*/CHANGELOG* only (no slash => repository root).
    if !p.contains('/') {
        let name = p.to_ascii_lowercase();
        return name.starts_with("readme") || name.starts_with("changelog");
    }

    false
}

/// Standard PR metadata block. Public-repo tooling parses the
/// `cogneva-bot-meta` marker to build the bot contribution board and to
/// attribute cross-validation comments; every line is single-valued and
/// missing data is rendered as `n/a`.
fn metadata_block(
    identity: &BotIdentityConfig,
    eval_note: Option<&str>,
    related: Option<&str>,
) -> String {
    let bot = identity
        .instance()
        .map(|i| i.handle)
        .unwrap_or_else(|| identity.git_author_name());
    format!(
        "<!-- cogneva-bot-meta -->\n\
         bot: {bot}\n\
         env: {env}\n\
         eval: {eval}\n\
         related: {related}",
        env = environment_summary(),
        eval = eval_note.unwrap_or("n/a"),
        related = related.unwrap_or("n/a"),
    )
}

/// One-line environment summary for the metadata block:
/// `<env>, <N>c/<M>G[, <deploy-profile>]`.
fn environment_summary() -> String {
    let env = std::env::var("COGNEVA_ENV").unwrap_or_else(|_| "prod".into());
    let cpus = std::thread::available_parallelism()
        .map(|n| n.get().to_string())
        .unwrap_or_else(|_| "?".into());
    let mem = mem_total_gib()
        .map(|m| m.to_string())
        .unwrap_or_else(|| "?".into());
    let mut summary = format!("{env}, {cpus}c/{mem}G");
    if let Ok(profile) = std::env::var("COGNEVA_DEPLOY_PROFILE") {
        if !profile.is_empty() {
            summary.push_str(&format!(", {profile}"));
        }
    }
    summary
}

/// Total RAM in whole GiB (rounded) from `/proc/meminfo`; `None` off Linux.
fn mem_total_gib() -> Option<u64> {
    let content = std::fs::read_to_string("/proc/meminfo").ok()?;
    for line in content.lines() {
        if let Some(rest) = line.strip_prefix("MemTotal:") {
            let kb: u64 = rest.split_whitespace().next()?.parse().ok()?;
            return Some((kb + 524_287) / 1_048_576);
        }
    }
    None
}

/// True when `workdir` looks like a usable git working copy.
pub async fn is_git_workdir(workdir: &Path) -> bool {
    workdir.join(".git").exists()
}

/// ChangeSink implementation that turns collaboration-generated changes into
/// GitHub pull requests (CI-failure fixes and other autonomous changes that
/// are not tied to an issue).
pub struct GitHubChangeSink {
    publisher: GitHubPrPublisher,
    provider: Arc<dyn CodePlatformProvider>,
    controller: Arc<crate::contribution::ContributionController>,
}

impl std::fmt::Debug for GitHubChangeSink {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GitHubChangeSink").finish_non_exhaustive()
    }
}

impl GitHubChangeSink {
    /// Create a sink from a publisher and the platform provider used to open
    /// pull requests. The controller carries the owner's contribution policy.
    pub fn new(
        publisher: GitHubPrPublisher,
        provider: Arc<dyn CodePlatformProvider>,
        controller: Arc<crate::contribution::ContributionController>,
    ) -> Self {
        Self {
            publisher,
            provider,
            controller,
        }
    }

    /// Whether `change_id` was already pushed as a `cogneva/auto-*` PR branch
    /// on the resolved push remote (upstream or the contributor's fork).
    pub(crate) async fn already_published(&self, change_id: &str) -> bool {
        let branch = format!("cogneva/auto-{}", sanitize(change_id));
        match self
            .publisher
            .prepare_push_remote(self.provider.as_ref())
            .await
        {
            Some(remote) => self.publisher.remote_branch_exists(remote, &branch).await,
            None => false,
        }
    }

    /// Publish a change regardless of the current policy: used when the owner
    /// explicitly approves a staged change (the click IS the decision).
    pub async fn publish_approved(&self, change: &GeneratedChange) -> cog_core::SFResult<String> {
        self.publish_pr(change).await
    }

    async fn publish_pr(&self, change: &GeneratedChange) -> cog_core::SFResult<String> {
        let branch = format!("cogneva/auto-{}", sanitize(&change.change_id));
        // Idempotency for the staged-change flush: a change re-submitted after a
        // restart (crash between push and housekeeping) already has its branch on
        // the remote. Re-pushing is rejected by --force-with-lease and re-opening
        // the PR errors, so an existing branch means "already published" — return
        // Ok so the staged file is dropped instead of looping the same failure.
        if self.already_published(&change.change_id).await {
            tracing::info!(
                change_id = %change.change_id,
                %branch,
                "change already published (remote branch exists); skipping duplicate PR"
            );
            return Ok(format!("existing:{branch}"));
        }
        let title = change
            .goal
            .lines()
            .next()
            .unwrap_or("autonomous change")
            .chars()
            .take(70)
            .collect::<String>();
        let mut body = String::new();
        // Link back to the tracked issue so competing solutions for the same
        // intent group together (bot board parses `Fixes #N`).
        if let Some(issue_number) = change.issue_number {
            body.push_str(&format!("Fixes #{issue_number}\n\n"));
        }
        body.push_str(&format!(
            "Change `{}` generated autonomously by Cogneva (PGE mode: {}).\n\n## Goal\n\n{}",
            change.change_id, change.pge_mode, change.goal
        ));
        if let Some(ref rationale) = change.rationale {
            body.push_str(&format!("\n\n## Rationale\n\n{rationale}"));
        }
        if let Some(score) = change.self_review_score {
            body.push_str(&format!("\n\nSelf-review score: {score:.2}"));
        }
        if !change.affected_files.is_empty() {
            body.push_str(&format!(
                "\n\nAffected files: {}",
                change.affected_files.join(", ")
            ));
        }

        let identity = &self.publisher.config.bot_identity;
        let eval_note = change
            .self_review_score
            .map(|score| format!("self-review={score:.2}"));
        let related = change.issue_number.map(|n| format!("#{n}"));
        body.push_str(&format!(
            "\n\n{}",
            metadata_block(identity, eval_note.as_deref(), related.as_deref())
        ));
        body.push_str(
            "\n\n---\nThis PR was generated autonomously by a Cogneva instance and is submitted under the instance owner's contribution policy.\n本 PR 由 Cogneva 实例自治演化产生，经属主授权策略自动提交。",
        );
        let commit_message = format!(
            "chore(cogneva): autonomous change {}\n\n{}\n\n{}",
            change.change_id,
            title,
            identity_signoff(identity)
        );

        let pr = self
            .publisher
            .publish(
                self.provider.as_ref(),
                &change.content,
                &branch,
                &commit_message,
                &format!("[Cogneva] {title}"),
                &body,
            )
            .await
            .map_err(|e| cog_core::SFError::Internal(e.to_string()))?;
        Ok(pr.url)
    }
}

#[async_trait::async_trait]
impl cog_core::ChangeSink for GitHubChangeSink {
    async fn submit_change(&self, change: GeneratedChange) -> cog_core::SFResult<String> {
        // Owner policy gate: Ask/Local stage the change instead of opening a
        // PR. Ask-mode entries surface in the UI and are flushed via
        // `publish_approved` when the owner approves.
        if self.controller.should_stage() {
            let path = crate::pending_changes::stage_change(&change).await?;
            tracing::info!(
                change_id = %change.change_id,
                policy = self.controller.policy().as_str(),
                "change staged by contribution policy"
            );
            return Ok(format!("staged:{}", path.display()));
        }
        self.publish_pr(&change).await
    }
}

/// Ensure `config.pr_workdir` is a usable git clone of the target repo.
///
/// Missing directories are created by cloning. Remote selection (first match
/// wins): `COGNEVA_GIT_PROXY_BASE` set → `{base}/github/{repo}.git` via the
/// security gateway, which injects credentials on egress so no secret enters
/// this process or the remote URL; `COGNEVA_GITHUB_USE_SSH` set →
/// `ssh://git@github.com:22/...` (authentication from `GIT_SSH_COMMAND`);
/// otherwise an `x-access-token` HTTPS remote when a platform token is
/// available, falling back to anonymous HTTPS.
///
/// In gateway-proxy mode an existing working copy's `origin` is rewritten to
/// the proxy URL (idempotent), so clones made with SSH/token remotes migrate
/// without a re-clone. Other modes leave existing remotes untouched.
pub async fn ensure_workdir(
    config: &GitHubIntegrationConfig,
    token: Option<&str>,
) -> Result<PathBuf> {
    let workdir = PathBuf::from(&config.pr_workdir);
    let url = remote_url(config, token);
    if is_git_workdir(&workdir).await {
        if git_proxy_base().is_some() {
            let output = tokio::process::Command::new("git")
                .args(["remote", "set-url", "origin", &url])
                .current_dir(&workdir)
                .output()
                .await?;
            if !output.status.success() {
                return Err(CogGitHubError::Provider(format!(
                    "git remote set-url failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                )));
            }
        }
        return Ok(workdir);
    }
    if let Some(parent) = workdir.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    let output = tokio::process::Command::new("git")
        .arg("clone")
        .arg(&url)
        .arg(&workdir)
        .output()
        .await?;
    if !output.status.success() {
        // Never leak the token into logs.
        let mut stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        if let Some(t) = token.filter(|t| !t.is_empty()) {
            stderr = stderr.replace(t, "***");
        }
        return Err(CogGitHubError::Provider(format!(
            "git clone failed: {stderr}"
        )));
    }
    Ok(workdir)
}

fn git_proxy_base() -> Option<String> {
    std::env::var("COGNEVA_GIT_PROXY_BASE")
        .ok()
        .filter(|s| !s.is_empty())
}

fn remote_url(config: &GitHubIntegrationConfig, token: Option<&str>) -> String {
    let repo = config.repo.clone();
    select_remote_url_for(
        config,
        token,
        git_proxy_base().as_deref(),
        std::env::var_os("COGNEVA_GITHUB_USE_SSH").is_some(),
        &repo,
    )
}

/// Build the git remote URL for `target_repo` (`owner/repo`). The fork remote
/// uses the same channel selection as origin: gateway proxy (credential-free
/// URL) first, then SSH, then token/anonymous HTTPS.
fn select_remote_url_for(
    _config: &GitHubIntegrationConfig,
    token: Option<&str>,
    proxy_base: Option<&str>,
    use_ssh: bool,
    target_repo: &str,
) -> String {
    if let Some(base) = proxy_base {
        return format!("{}/github/{}.git", base.trim_end_matches('/'), target_repo);
    }
    if use_ssh {
        return format!("ssh://git@github.com:22/{target_repo}.git");
    }
    match token {
        Some(t) => format!("https://x-access-token:{t}@github.com/{target_repo}.git"),
        None => format!("https://github.com/{target_repo}.git"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_strips_unsafe_chars() {
        assert_eq!(sanitize("change-AB_12/.."), "change-AB_12");
    }

    fn diff_touching(paths: &[&str]) -> String {
        paths
            .iter()
            .map(|p| format!("--- a/{p}\n+++ b/{p}\n@@ -1 +1 @@\n-old\n+new\n"))
            .collect()
    }

    #[test]
    fn whitelist_allows_generic_code_prompt_and_root_docs() {
        assert!(is_allowed_path("crates/cog-github/src/lib.rs"));
        assert!(is_allowed_path(
            "crates/cog-core/src/contract/reflection.rs"
        ));
        assert!(is_allowed_path("./crates/cog-github/src/webhook.rs"));
        assert!(is_allowed_path("prompts/change-generator.md"));
        assert!(is_allowed_path("prompts/roundtable/system.txt"));
        assert!(is_allowed_path("README.md"));
        assert!(is_allowed_path("README"));
        assert!(is_allowed_path("CHANGELOG.md"));
        assert!(is_allowed_path("changelog"));
    }

    #[test]
    fn whitelist_rejects_private_infra_config_and_secrets() {
        let denied = [
            "deploy/helm/cogneva/values.yaml",
            "deploy/k3s/cogneva.yaml",
            ".github/workflows/release.yml",
            "crates/cog-github/tests/it.rs",
            "crates/cog-github/build.rs",
            "crates/cog-github/Cargo.toml",
            "Cargo.toml",
            "cogneva.json",
            "docs/setup.md",
            "secrets/id_rsa",
            "deploy/certs/server.pem",
            "src/main.rs",
            "crates/cog-github/src",
            "prompts/../etc/passwd",
        ];
        for path in denied {
            assert!(!is_allowed_path(path), "should deny {path}");
        }
    }

    #[test]
    fn privacy_gate_accepts_whitelisted_diff() {
        let diff = diff_touching(&[
            "crates/cog-github/src/pr_publisher.rs",
            "crates/cog-core/src/lib.rs",
            "prompts/evaluator.md",
            "README.md",
        ]);
        ensure_contribution_allowed(&diff).unwrap();
    }

    #[test]
    fn privacy_gate_rejects_diff_with_any_non_whitelisted_path() {
        let diff = diff_touching(&[
            "crates/cog-github/src/lib.rs",
            "deploy/helm/cogneva/values.yaml",
        ]);
        let err = ensure_contribution_allowed(&diff).unwrap_err();
        match err {
            CogGitHubError::PrivacyRejected(msg) => {
                assert!(msg.contains("deploy/helm/cogneva/values.yaml"));
                assert!(msg.contains("whitelist"));
            }
            other => panic!("expected PrivacyRejected, got {other:?}"),
        }
    }

    #[test]
    fn privacy_gate_fails_closed_on_unparseable_diff() {
        let err = ensure_contribution_allowed("not a diff at all").unwrap_err();
        assert!(matches!(err, CogGitHubError::PrivacyRejected(_)));
    }

    #[test]
    fn metadata_block_uses_instance_handle_when_present() {
        let identity = BotIdentityConfig {
            fingerprint: Some(
                "a3f9d2c1a3f9d2c1a3f9d2c1a3f9d2c1a3f9d2c1a3f9d2c1a3f9d2c1a3f9d2c1".into(),
            ),
            ..Default::default()
        };
        let block = metadata_block(&identity, Some("self-review=0.87"), Some("#42 (by Bob)"));
        assert!(block.starts_with("<!-- cogneva-bot-meta -->"));
        assert!(block.contains(&format!("bot: {}", identity.git_author_name())));
        assert!(block.contains("self-review=0.87"));
        assert!(block.contains("#42 (by Bob)"));
        assert_eq!(block.lines().count(), 5);
        // env line shape: "<env>, <n>c/<m>G".
        let env_line = block.lines().find(|l| l.starts_with("env: ")).unwrap();
        assert!(env_line.contains("c/"));
        assert!(env_line.ends_with('G') || env_line.contains("G,"));
    }

    #[test]
    fn metadata_block_falls_back_to_static_identity_and_na_fields() {
        let identity = BotIdentityConfig::default();
        let block = metadata_block(&identity, None, None);
        assert!(block.contains("bot: Cogneva Bot"));
        assert!(block.contains("eval: n/a"));
        assert!(block.contains("related: n/a"));
    }

    #[test]
    fn remote_url_selection_priority() {
        let config = GitHubIntegrationConfig {
            repo: "o/r".into(),
            ..Default::default()
        };
        // 网关代理优先于一切，URL 不含任何凭证。
        assert_eq!(
            select_remote_url_for(
                &config,
                Some("tok"),
                Some("http://gw:8081/git"),
                false,
                "o/r"
            ),
            "http://gw:8081/git/github/o/r.git"
        );
        // 尾斜杠归一。
        assert_eq!(
            select_remote_url_for(&config, None, Some("http://gw:8081/git/"), true, "o/r"),
            "http://gw:8081/git/github/o/r.git"
        );
        // 无代理时 SSH 优先于 token HTTPS。
        assert_eq!(
            select_remote_url_for(&config, Some("tok"), None, true, "o/r"),
            "ssh://git@github.com:22/o/r.git"
        );
        assert_eq!(
            select_remote_url_for(&config, Some("tok"), None, false, "o/r"),
            "https://x-access-token:tok@github.com/o/r.git"
        );
        assert_eq!(
            select_remote_url_for(&config, None, None, false, "o/r"),
            "https://github.com/o/r.git"
        );
        // fork 坐标走同一套通道选择，仅仓库段换成 fork。
        assert_eq!(
            select_remote_url_for(
                &config,
                Some("tok"),
                Some("http://gw:8081/git"),
                false,
                "alice/r"
            ),
            "http://gw:8081/git/github/alice/r.git"
        );
        assert_eq!(
            select_remote_url_for(&config, Some("tok"), None, false, "alice/r"),
            "https://x-access-token:tok@github.com/alice/r.git"
        );
    }

    #[test]
    fn push_target_head_and_remote() {
        assert_eq!(PushTarget::Upstream.remote(), "origin");
        assert_eq!(
            PushTarget::Upstream.pr_head("cogneva/auto-x"),
            "cogneva/auto-x"
        );
        let fork = PushTarget::Fork(ForkTarget {
            owner: "alice".into(),
            full_name: "alice/r".into(),
            newly_created: false,
        });
        assert_eq!(fork.remote(), "fork");
        assert_eq!(fork.pr_head("cogneva/auto-x"), "alice:cogneva/auto-x");
    }
}
