//! PR publisher — turns a generated patch into a pull request.
//!
//! Flow (design doc §3.7): branch from `base_branch` in a local working
//! copy → `git apply` the unified diff → commit signed as the bot identity
//! → push → open the PR via the platform provider.
//!
//! The working copy must be a git clone of the target repository with a
//! push-capable `origin` remote; credentials stay in the main process and
//! never enter the sandbox.

use std::path::{Path, PathBuf};

use cog_core::{BotIdentityConfig, GitHubIntegrationConfig};

use crate::error::{CogGitHubError, Result};
use crate::provider::{CodePlatformProvider, CreatePullRequest, PlatformPullRequest};

/// Publishes patches as pull requests.
pub struct GitHubPrPublisher {
    workdir: PathBuf,
    config: GitHubIntegrationConfig,
}

impl GitHubPrPublisher {
    /// Create a publisher operating on the given local working copy.
    pub fn new(workdir: impl Into<PathBuf>, config: GitHubIntegrationConfig) -> Self {
        Self {
            workdir: workdir.into(),
            config,
        }
    }

    /// Apply `patch_content` on a fresh branch and open a PR linking
    /// `issue_number`. Returns the created PR.
    pub async fn publish_patch(
        &self,
        provider: &dyn CodePlatformProvider,
        patch_id: &str,
        patch_content: &str,
        issue_number: u64,
        issue_title: &str,
    ) -> Result<PlatformPullRequest> {
        let branch = format!("cogneva/fix-{}-{}", issue_number, sanitize(patch_id));
        let identity = &self.config.bot_identity;

        self.git(&["checkout", &self.config.base_branch.clone()])
            .await?;
        self.git(&["checkout", "-B", &branch]).await?;

        let apply_result = self.apply_patch(patch_content).await;
        if let Err(e) = apply_result {
            // Best-effort cleanup so the next attempt starts clean.
            let _ = self
                .git(&["checkout", &self.config.base_branch.clone()])
                .await;
            let _ = self.git(&["branch", "-D", &branch]).await;
            return Err(e);
        }

        self.git(&["add", "-A"]).await?;
        self.git(&[
            "-c",
            &format!("user.name={}", identity.name),
            "-c",
            &format!("user.email={}", identity.email),
            "commit",
            "-m",
            &format!(
                "fix(issue #{}): {}\n\nAutomated patch {} generated by Cogneva.\n\n{}",
                issue_number,
                issue_title,
                patch_id,
                identity_signoff(identity)
            ),
        ])
        .await?;
        self.git(&["push", "-u", "origin", &branch, "--force-with-lease"])
            .await?;

        let pr = provider
            .create_pull_request(CreatePullRequest {
                title: format!("[Cogneva] fix issue #{}: {}", issue_number, issue_title),
                body: format!(
                    "Fixes #{}\n\nPatch `{}` generated autonomously by Cogneva.\n\n{}",
                    issue_number, patch_id, self.config.conversation.bot_signature
                ),
                head_branch: branch,
                base_branch: self.config.base_branch.clone(),
                draft: false,
            })
            .await?;

        Ok(pr)
    }

    async fn apply_patch(&self, patch_content: &str) -> Result<()> {
        let tmp = tempfile::NamedTempFile::new()?;
        std::fs::write(tmp.path(), patch_content)?;
        let output = tokio::process::Command::new("git")
            .arg("apply")
            .arg("--whitespace=nowarn")
            .arg(tmp.path())
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git apply failed: {}",
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }

    async fn git(&self, args: &[&str]) -> Result<()> {
        let output = tokio::process::Command::new("git")
            .args(args)
            .current_dir(&self.workdir)
            .output()
            .await?;
        if !output.status.success() {
            return Err(CogGitHubError::Provider(format!(
                "git {:?} failed: {}",
                args,
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(())
    }
}

fn sanitize(patch_id: &str) -> String {
    patch_id
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '-' | '_'))
        .collect()
}

fn identity_signoff(identity: &BotIdentityConfig) -> String {
    format!("Signed-off-by: {} <{}>", identity.name, identity.email)
}

/// True when `workdir` looks like a usable git working copy.
pub async fn is_git_workdir(workdir: &Path) -> bool {
    workdir.join(".git").exists()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_strips_unsafe_chars() {
        assert_eq!(sanitize("patch-AB_12/.."), "patch-AB_12");
    }
}
