//! 构建期把部署资产（预渲染清单、init-secrets 脚本、helm chart）打进二进制，
//! 让预编译引导器不依赖源码树即可完成 apply/helm 两条投递路径。
//!
//! 生成 $OUT_DIR/bootstrap_assets.rs，内容为 (相对仓库根路径, include_bytes!)
//! 列表；运行时解包到临时工作目录并把 COGNEVA_REPO_ROOT 指过去，既有磁盘
//! 路径逻辑保持不变。

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir.join("../..");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // (相对仓库根的路径, 是否递归目录)
    let asset_roots: &[(&str, bool)] = &[
        ("deploy/rendered/k3s-single", true),
        ("deploy/rendered/k3s-multi", true),
        ("deploy/rendered/k8s-standard", true),
        ("deploy/scripts/init-secrets.sh", false),
        ("deploy/helm/cogneva", true),
    ];

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for (rel, recursive) in asset_roots {
        let abs = repo_root.join(rel);
        if *recursive {
            collect_files(&repo_root, &abs, &mut entries);
        } else {
            entries.push((rel.to_string(), abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::from(
        "// Auto-generated by crates/bootstrap/build.rs — do not edit.\n\
         pub const EMBEDDED_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &entries {
        // 逐文件声明 rerun-if-changed：目录级声明感知不到深层文件的内容变化
        println!("cargo:rerun-if-changed={}", abs.display());
        let path = abs.to_string_lossy().replace('\\', "/");
        let rel = rel.replace('\\', "/");
        generated.push_str(&format!("    ({rel:?}, include_bytes!({path:?})),\n"));
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("bootstrap_assets.rs"), generated).unwrap();
}

fn collect_files(repo_root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("读取资产目录 {} 失败: {e}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_files(repo_root, &path, out);
        } else {
            let rel = path.strip_prefix(repo_root).unwrap().to_path_buf();
            out.push((rel.to_string_lossy().replace('\\', "/"), path));
        }
    }
}
