//! Plugin registry — auto-generated by `build.rs`.
//! Do not edit this file manually.  Add/remove plugin crates in
//! `Cargo.toml` only; init order is derived at runtime by topological sort.

include!(concat!(env!("OUT_DIR"), "/plugin_registry_generated.rs"));
